nome = input('Qual é o seu nome? ')
idade = input('Qual é a sua idade?')
altura = input('Qual é a sua altura? ')
print('Nome: ', nome)
print('Idade: ', idade)
print('Altura: ', altura)
print('Olá, mundo!')